# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hipster-frontend
spec:
  selector:
    matchLabels:
      app: hipster-frontend
  template:
    metadata:
      labels:
        app: hipster-frontend
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - name: server
          image: app
          ports:
          - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
              - name: "Cookie"
                value: "shop_session-id=x-readiness-probe"
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
              - name: "Cookie"
                value: "shop_session-id=x-liveness-probe"
          env:
          - name: ENVIRONMENT
            value: base
          - name: PORT
            value: "8080"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice.hipster-shop.svc.cluster.local:3550"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice.hipster-shop.svc.cluster.local:7000"
          - name: CART_SERVICE_ADDR
            value: "cartservice.hipster-shop.svc.cluster.local:7070"
          - name: RECOMMENDATION_SERVICE_ADDR
            value: "recommendationservice.hipster-shop.svc.cluster.local:8080"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice.hipster-shop.svc.cluster.local:50051"
          - name: CHECKOUT_SERVICE_ADDR
            value: "checkoutservice.hipster-shop.svc.cluster.local:5050"
          - name: AD_SERVICE_ADDR
            value: "adservice.hipster-shop.svc.cluster.local:9555"
          # - name: DISABLE_TRACING
          #   value: "1"
          # - name: DISABLE_PROFILER
          #   value: "1"
          # - name: JAEGER_SERVICE_ADDR
          #   value: "jaeger-collector:14268"
          resources:
            requests:
              cpu: 200m
              memory: 180Mi
            limits:
              cpu: 300m
              memory: 300Mi
