# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include:
- project: 'platform-admins/shared-ci-cd'
  file: 'cd/gke-deploy.yaml'

deploy-staging-us-west2:
  tags:
  - cluster:staging-us-west2, app:APP_NAME

deploy-prod-us-central1:
  tags:
  - cluster:prod-us-central1, app:APP_NAME

deploy-prod-us-east1:
  tags:
  - cluster:prod-us-east1, app:APP_NAME

stages:
  - deploy-staging-us-west2
  - deploy-prod-us-central1
  - rollout-approval
  - deploy-prod-us-east1
